### ISSUE TITLE
.tests-env-2

### ISSUE THREAD

**Issue by nazariyv** [gitcoinco/governance#11]
Is it possible to commit that file, please? :)

https://github.com/gitcoinco/governance/blob/main/tests/TokenDistributor_test.py#L17

**Comment by nopslip** [comment]
Sorry for the delayed reply. I've committed a sample test file for reference here - https://github.com/gitcoinco/governance/commit/d5362d31076e79e76503ff845d8475473b53a3fd 

It looks like you probably already got this working but please let me know if you need anything else for the tests.
